package tinylangparser;

public enum TinyLangAstNodes {
	//program node
	TINY_LANG_PROGRAM_NODE,
	//statement nodes
	AST_VARIABLE_DECLARATION_NODE,
	AST_ASSIGNMENT_NODE,
	AST_PRINT_STATEMENT_NODE,
	AST_IF_STATEMENT_NODE,
	AST_FOR_STATEMENT_NODE,
	AST_WHILE_STATEMENT_NODE,
	AST_RETURN_STATEMENT_NODE,
	AST_FUNCTION_DECLARATION_NODE,
	AST_BLOCK_NODE,
	AST_ELSE_BLOCK_NODE,	
	//expression nodes
	AST_BINARY_OPERATOR_NODE,
	AST_UNARY_OPERATOR_NODE,
	AST_FUNCTION_CALL_NODE,
	//literal nodes
	AST_BOOLEAN_LITERAL_NODE,
	AST_INTEGER_LITERAL_NODE,
	AST_FLOAT_LITERAL_NODE,
	AST_CHAR_LITERAL_NODE,
	//parameters nodes
	AST_ACTUAL_PARAMETERS_NODE,
	AST_FORMAL_PARAMETERS_NODE,
	AST_FORMAL_PARAMETER_NODE,
	//type node
	AST_TYPE_NODE,
	//expression nodes
	//expression nodes leaves
	AST_IDENTIFIER_NODE
}
